version: '3'

services:
  db:
    image: postgres
    container_name: db_app
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: habits_drf
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    ports:
      - '5433:5433'

  redis:
    image: redis
    container_name: redis_app
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - '8001:8001'
    volumes:
      - ./data/cache:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    build: .
    container_name: app_container
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis
    volumes:
      - ./.env:/app/.env

  celery:
    build: .
    container_name: celery_app
    command: celery -A config worker -l INFO --loglevel warning
    volumes:
      - celery_data:/app
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_LOG_LEVEL=debug
    healthcheck:
      test: [ "CMD", "celery", "inspect", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  celery-beat:
      build: .
      container_name: celery_beat_app
      command: celery -A config beat -l info -S django --loglevel warning
      volumes:
        - celery_beat_data:/app
      depends_on:
        redis:
          condition: service_healthy
        celery:
          condition: service_healthy
      environment:
        - CELERY_BROKER_URL=redis://redis:6379/0
        - CELERY_LOG_LEVEL=debug

volumes:
  postgres_data:
  redis_data:
  celery_data:
  celery_beat_data: