# Generated by Django 4.2.3 on 2023-07-30 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50, verbose_name='место')),
                ('moment', models.TimeField(verbose_name='время')),
                ('action', models.CharField(max_length=255, verbose_name='действие')),
                ('is_nice', models.BooleanField(default=False, verbose_name='признак приятной привычки')),
                ('interval', models.CharField(choices=[('раз в день', 'раз в день'), ('раз в два дня', 'раз в два дня'), ('раз в три дня', 'раз в три дня'), ('раз в четыре дня', 'раз в четыре дня'), ('раз в пять дней', 'раз в пять дней'), ('раз в шесть дней', 'раз в шесть дней'), ('раз в неделю', 'раз в неделю')], default='раз в день', verbose_name='периодичность выполнения')),
                ('run_time', models.IntegerField(default=120, verbose_name='время выполнения в секундах')),
                ('is_published', models.BooleanField(default=False, verbose_name='опубликованно')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='действие')),
                ('habit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='связанная привычка')),
            ],
        ),
    ]
