# Generated by Django 4.2.3 on 2023-07-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='reward',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='вознаграждение'),
        ),
    ]
