# Generated by Django 4.2.3 on 2023-07-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habit_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedhabit',
            name='is_nice',
            field=models.BooleanField(default=False, verbose_name='признак приятной привычки'),
        ),
    ]
