# Generated by Django 4.2.3 on 2023-07-31 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_relatedhabit_is_nice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'verbose_name': 'привычка', 'verbose_name_plural': 'привычки'},
        ),
        migrations.AlterModelOptions(
            name='relatedhabit',
            options={'verbose_name': 'связанная привыка', 'verbose_name_plural': 'связанные привычки'},
        ),
    ]
