# Generated by Django 4.2.3 on 2023-07-30 16:46

from django.db import migrations, models
import habits.validators


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_relatedhabit_is_nice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'verbose_name': 'привычка', 'verbose_name_plural': 'привычки'},
        ),
        migrations.AlterModelOptions(
            name='relatedhabit',
            options={'verbose_name': 'связанная привыка', 'verbose_name_plural': 'связанные привычки'},
        ),
        migrations.AlterField(
            model_name='habit',
            name='run_time',
            field=models.IntegerField(default=120, validators=[habits.validators.is_to_long], verbose_name='время выполнения в секундах'),
        ),
        migrations.AlterField(
            model_name='relatedhabit',
            name='is_nice',
            field=models.BooleanField(default=False, validators=[habits.validators.is_nice_validator], verbose_name='признак приятной привычки'),
        ),
    ]
