# Generated by Django 4.2.3 on 2023-07-31 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_alter_habit_options_alter_relatedhabit_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedhabit',
            name='habit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='habit', to='habits.habit', verbose_name='связанная привычка'),
        ),
    ]
